FROM oven/bun:1.1.30-slim

WORKDIR /app

COPY package*.json ./
COPY pnpm-workspace.yaml ./
COPY turbo.json ./

COPY ./packages ./packages

RUN mkdir -p ./apps/web

COPY ./apps/web/package.json ./apps/web/
COPY ./apps/web/tsconfig.json ./apps/web/

RUN bun install

COPY ./apps/web ./apps/web

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start"]